---
title: "GLM NNL Database"
author: "Nicole Shumway"
date: "19 August 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---

#Load packages
```{r setup}


library("Hmisc")
library("MASS")
library("AER")
library("ggplot2")

```


##Load Data
```{r }

Policy_Analysis <- read.csv("C:/Users/uqnshumw/OneDrive - The University of Queensland/Documents/Git/Marine-NNL-database/Policy_Analysis.csv")


#WGI_analysis <- read.csv("C:/Users/uqnshumw/OneDrive - The University of Queensland/PhD Research/Ch. 1a Marine NNL Policy Review/WGI_analysis.csv")
View(WGI_Analysis)

```


#Correlation Matrix - ALL DATA

```{r}

head(Policy_Analysis)
Policy_data <- Policy_Analysis[,4:length(Policy_Analysis)] ## makes a new dataframe from policy analysis, subsets everything to the right of presence/absence
View(Policy_data)


round(cor(Policy_data, use = "na.or.complete"),2) ##rounds the date two decimal places for clarity
cor_matrix <- cor(Policy_data, use="pairwise.complete.obs", method = c("spearman"))   
View(cor_matrix)



```


### Make Generalized linear model of all data against presence/absence of policy ####

```{r}

All_Model <- glm(Policy_Analysis$Presence_Absence ~ Policy_Analysis$Richness + Policy_Analysis$mam_bird + Policy_Analysis$EEZ_Protected
                    + Policy_Analysis$Polity2 + Policy_Analysis$GDP +Policy_Analysis$ + Policy_Analysis$Rents + Policy_Analysis$OHI, family = "binomial", data = Policy_Analysis)
summary(All_Model)

#plot(All_Model)
```



```{r}


#####################################
#####BIODIVERSITY VALUES#############
#####################################


### GLM of Marine variables#####
Marine_model <- glm(Policy_Analysis$Presence_Absence ~ Policy_Analysis$mam_bird +Policy_Analysis$EEZ_Protected +Policy_Analysis$Richness+Policy_Analysis$OHI, family = "binomial", data = Policy_Analysis)
summary(Marine_model)

## GLM of response to threat###
Threat_model <- glm(Policy_Analysis$Presence_Absence ~ Policy_Analysis$mam_bird, family = "binomial", data = Policy_Analysis )
summary(Threat_model)

###GLM of Response to protection####
Protection_model <- glm(Policy_Analysis$Presence_Absence ~ Policy_Analysis$EEZ_Protected, family = "binomial", data = Policy_Analysis)
summary(Protection_model)


###GLM of Response to presence of biodiversity 
Biodiversity_model <- glm(Policy_Analysis$Presence_Absence ~ Policy_Analysis$Richness + Policy_Analysis$OHI, family = "binomial", data = Policy_Analysis)
summary(Biodiversity_model)


```


```{r}

#####################################
#####SOCIO-POLITICAL VALUES##########
#####################################

### All Variables ###

Policy_model <- glm(Policy_Analysis$Presence_Absence ~ Policy_Analysis$Polity2 + log(Policy_Analysis$GDP) + Policy_Analysis$Rents, family = "binomial", data = Policy_Analysis)
summary(Policy_model)

### getting a warning message: "glm.fit: fitted probabilities numerically 0 or 1 occurred" - log transformed GDP, no longer getting fit error

## Government Capacity###
Capacity_Model <- glm(Policy_Analysis$Presence_Absence ~ Policy_Analysis$Polity2 + log(Policy_Analysis$GDP), family = "binomial", data = Policy_Analysis)
summary(Capacity_Model)

```


```{r}


######WGI VARIABLES #########

### GLM of Response to World Governance Indicators ##
#WGI_model <- glm(WGI_Analysis$Presence_Absence ~ WGI_Analysis$Control.of.Corruption + WGI_Analysis$Government.Effectiveness + WGI_Analysis$Political.Stability.Absense.of.Violence + WGI_Analysis$Regulatory.Quality + WGI_Analysis$Rule.of.Law + WGI_Analysis$Voice.Accountability, family = "binomial", data = WGI_Analysis)
#summary(WGI_model)

#WGI_Analysis$STAGE = factor(WGI_Analysis$STAGE, levels = c("None", "Potential", "Preliminary", "In Progress", "Established") )


#WGI_Stage <- polr(WGI_Analysis$STAGE ~  WGI_Analysis$Control.of.Corruption + WGI_Analysis$Government.Effectiveness +
                   # WGI_Analysis$Political.Stability.Absense.of.Violence + WGI_Analysis$Regulatory.Quality +
                   # WGI_Analysis$Rule.of.Law + WGI_Analysis$Voice.Accountability, data = WGI_Analysis, Hess = TRUE) 
#summary(WGI_Stage) 
#coeftest(WGI_Stage)

```


#Ordinal Logistic Regression
```{r}

#To describe or predict variables. OLR can id which variables predict the level of involvement in offsets policy

#Dividing data into training and test set
#Random sampling
#samplesize = .60*nrow(Policy_data)
#index = sample(seq_len(nrow(Policy_data)), size = samplesize)
#Creating training and test set 
#datatrain <- Policy_Analysis[index,]
#datatest <- Policy_Analysis[-index,]



## Build ordinal logistic regression model

### Stage of Policy vs. ALL values ###


Policy_Analysis$STAGE2 = factor(Policy_Analysis$STAGE2, levels = c("0", "1", "2", "3", "4") )

All_Stage <- polr(Policy_Analysis$STAGE2 ~  Policy_Analysis$mam_bird +Policy_Analysis$EEZ_Protected +
                      Policy_Analysis$OHI + log(Policy_Analysis$GDP) + 
                      Policy_Analysis$Polity2 + Policy_Analysis$Richness, data = Policy_Analysis, Hess = TRUE) ##DRopped Richness and NRR not significant
summary(All_Stage) 
coeftest(All_Stage)

#confidence intervals
ci_All <- confint(All_Stage)


#After building the model and interpreting the model, the next step is to evaluate it. 
  #The evaluation of the model is conducted on the test dataset. A basic evaluation approach is to compute the confusion matrix and the misclassification error. 

#Compute confusion table and misclassification error - model predicts 0,1 bette
predictstage = predict(All_Stage,Policy_Analysis)
table(Policy_Analysis$STAGE2, predictstage)
mean(as.character(Policy_Analysis$STAGE2) != 
       as.character(predictstage))


```



##Stage of Policy vs Poltical values
```{r}


#For predicting
#Dividing data into training and test set
#Random sampling
##samplesize = .60*nrow(Policy_Analysis)
##index = sample(seq_len(nrow(Policy_Analysis)), size = samplesize)
#Creating training and test set 
##datatrain <- Policy_Analysis[index,]
##datatest <- Policy_Analysis[-index,]

Policy_Analysis$STAGE2 = factor(Policy_Analysis$STAGE2, levels = c("0", "1", "2", "3", "4") )

Policy_Stage <- polr(STAGE2 ~  log(GDP) + Polity2, data = Policy_Analysis, Hess = TRUE)

summary(Policy_Stage)
coeftest(Policy_Stage)

#After building the model and interpreting the model, the next step is to evaluate it. 
#The evaluation of the model is conducted on the test dataset. A basic evaluation approach is to compute the confusion matrix and the misclassification error. 

#For predicting
#Compute confusion table and misclassification error - model predicts lo
#predictstage2 = predict(Policy_Stage,Policy_Analysis)
#table(Policy_Analysis$STAGE2, predictstage2)
#mean(as.character(Policy_Analysis$STAGE2) != as.character(predictstage2))


```


##Plotting the effects
```{r}

## this isn't working - getting log(GDP) predictor is not in the model?
library("effects")
Effect(focal.predictors = "log(GDP)",Policy_Stage)
plot(Effect(focal.predictors = "log(GDP)",Policy_Stage))
plot(Effect(focal.predictors = c("log(GDP)", "Polity2)",Policy_Stage)))

###


```


##Plot
```{r}

boxplot(Policy_Analysis$STAGE ~ Policy_Analysis$EEZ_Protected + Policy_Analysis$Polity2 + Policy_Analysis$GDP + Policy_Analysis$OHI, data = Policy_Analysis, main = "Stage vs Variables", xlab="Variables", ylab= "Stage")

boxplot(Policy_Analysis$Polity2 ~ Policy_Analysis$STAGE, data = Policy_Analysis, id.n=TRUE, main = "Polity2 Index vs Stage", xlab="Stage", ylab= "Polity2 score")
```


##plot

```{r}

### GLM of OHI ### Why signigican in Policy model but not here?

OHI_Model <- glm(formula = Policy_Analysis$Presence_Absence ~ Policy_Analysis$OHI, family = binomial, data = Polity_Analysis)
summary (OHI_Model)
plot(OHI_Model)
boxplot(Policy_Analysis$OHI ~ Policy_Analysis$STAGE, data = Policy_Analysis, main = "Stage vs OHI", xlab="stage", ylab= "OHI")

##########
Model2 <- lm(formula = Policy_Analysis$Presence_Absence ~ Policy_Analysis$Polity2 + Policy_Analysis$GDP + Policy_Analysis$NRR + Policy_Analysis$OHI + Policy_Analysis$Land_Protected, data = Policy_Analysis)
summary(Model2)

######
Polity_model <- lm(formula = Policy_Analysis$Presence_Absence ~ Policy_Analysis$Polity2, data = Policy_Analysis)
summary (Polity_model)
plot(Policy_Analysis$Presence_Absence ~ Policy_Analysis$Polity2, data = Policy_Analysis)
abline(Polity_model)

### lm of country vs. % EEZ Protected ####
fit2 <- lm(formula = Policy_Analysis$Presence_Absence ~ Policy_Analysis$EEZ_Protected, data = Policy_Analysis)
summary (fit2)
plot(Policy_Analysis$Presence_Absence ~ Policy_Analysis$EEZ_Protected, data = Policy_Analysis)
abline(fit2)

### plotting interactions ######
Int1 <- lm(formula = Policy_Analysis$Presence_Absence ~ Policy_Analysis$Polity2*Policy_Analysis$OHI, data = Policy_Analysis)
summary(Int1)

Int2 <- lm(formula = Policy_Analysis$Presence_Absence ~ Policy_Analysis$Polity2*Policy_Analysis$Species_risk, data = Policy_Analysis)
summary(Int2)
interaction.plot(Policy_Analysis$Presence_Absence, Policy_Analysis$Polity2, Policy_Analysis$Species_risk)

```



#Plots
##Load packages
```{r}

library(tidyverse)
library(ggplot2)
library(RColorBrewer)

```


```{r}
#### Boxplot of Presence/Absence vs. Polity 2 - Y axis first then x (response)
boxplot(Policy_Analysis$Polity2 ~ Policy_Analysis$Presence_Absence, data = Policy_Analysis, main = "Polity2 Index", xlab="Policy", ylab= "Polity2 score")

boxplot(log(Policy_Analysis$GDP) ~ Polity_Analysis$Presence_Absence, data = Policy_Analysis, main = "Presence vs GDP", xlab="Presence", ylab= "log(GDP)")

boxplot(log(Policy_Analysis$EEZ_Protected) ~ Polity_Analysis$Presence_Absence, data = Policy_Analysis, main = "Presence vs EEZ", xlab="Presence", ylab= "log(EEZ)")

boxplot(Policy_Analysis$Richness ~ Policy_Analysis$STAGE, ylim= c(0,1), data = Policy_Analysis, main = "STAGE vs Richness", xlab="Stage", ylab= "Richness")


### plotting stage vs GDP - cut into quartiles
plot(Policy_Analysis$STAGE ~ log(Policy_Analysis$GDP), data = Policy_Analysis)
grid(2,2)
identify(log(Policy_Analysis$GDP), Policy_Analysis$STAGE, labels = row.names (Policy_Analysis$GI), plot = TRUE, tolerance = .25) #not working


plot(Policy_Analysis$Polity2~ log(Policy_Analysis$GDP), data = Policy_Analysis)
grid(2,2)

##ggplot
library("ggplot2")
library("scales")

#Policy_Analysis$GDP = as.numeric(levels(Policy_Analysis$GDP))[Policy_Analysis$GDP]


ggplot(data=Policy_Analysis, aes(x=log(GDP), y=Polity2, color=Policy_Analysis$Presence_Absence)) + 
  geom_point(size = 3) +
  xlab("logGDP") +
  ylab("Polity 2 Score") +
  theme_classic() + xlim(20,31) +
  guides(color = guide_legend(title = "Policy Presence"))
  #geom_hline(data = Policy_Analysis, aes(yintercept = as.numeric(0)), color= "red")) + # code for quartile not working
  #geom_vline(data = Policy_Analysis, aes(xintercept = as.numeric(median(log(Policy_Analysis$GDP))), color = "red")) #code for quartile not working
##+ panel.grid.major = element_line(colour = "firebrick", size = 4) - not working

#geom_vline(xintercept = as.numeric(median(log(Policy_Analysis$GDP))), color = "red"))

#3d Scatter plot

library(scatterplot3d)
attach(Policy_Analysis)
scatterplot3d(Policy_Analysis$STAGE, Policy_Analysis$GDP, Policy_Analysis$Polity2, main = "3D Scatterplot")


```


